name: Core Dumps
description: Enable or analyze and upload core dumps.
author: support@senzing.com

inputs:
  analyze-core-dumps:
    description: Run analysis and upload core dump after running build/test.
  core-file-suffix:
    description: Suffix for core dump artifact names. Used with analyze only.
    required: false
  enable-core-dumps:
    description: Enable core dumps on a system before running build/test.

runs:
  using: composite
  steps:
    - if: runner.os == 'Linux'
      name: Run on Linux
      uses: senzing-factory/github-action-core-dumps/linux@v1
      with:
        analyze-core-dumps: "${{ inputs.analyze-core-dumps }}"
        core-file-suffix: "${{ inputs.core-file-suffix }}"
        enable-core-dumps: "${{ inputs.enable-core-dumps }}"

    - if: runner.os == 'macOS'
      name: Run on macOS
      uses: senzing-factory/github-action-core-dumps/macos@v1
      with:
        analyze-core-dumps: "${{ inputs.analyze-core-dumps }}"
        core-file-suffix: "${{ inputs.core-file-suffix }}"
        enable-core-dumps: "${{ inputs.enable-core-dumps }}"

    - if: runner.os == 'Windows'
      name: Run on Windows
      uses: senzing-factory/github-action-core-dumps/windows@v1
      with:
        analyze-core-dumps: "${{ inputs.analyze-core-dumps }}"
        core-file-suffix: "${{ inputs.core-file-suffix }}"
        enable-core-dumps: "${{ inputs.enable-core-dumps }}"

branding:
  icon: bug
  color: green
